### ISSUE TITLE
Et avec le smartphone ?

### ISSUE THREAD

**Issue by Oliviercreativ** [r0mdau/flashsms#3]
Bonjour, je voudrais savoir si on connecte son smartphone au RPI en partageant ma connexion via USB, est ce que c'est possible d'envoyer des SMS avec flashsms s'il vous plaît ?

Merci

**Comment by r0mdau** [comment]
Bonjour,

Attention, le code n'est plus maintenu depuis quelques temps.

Si gammu est capable de communiquer avec votre téléphone (ce qui m'étonnerai) alors oui.
Gammu est le logiciel a installer sur la raspbian, il permet de communiquer avec des dongle usb sur lesquels on branche directement une carte sim.

Cordialement.

**Comment by Oliviercreativ** [comment]
ok j'ai compris ! merci de la réponse
